language: objective-c
osx_image: xcode7.3

env:
  global:
    - LC_CTYPE=en_US.UTF-8

script:
  - pod lib lint --allow-warnings
  - set -o pipefail
  - xcodebuild test -scheme Alembic-OSX -configuration Release  | xcpretty -c
  - xcodebuild test -scheme Alembic-iOS -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' | xcpretty - c
  - xcodebuild build -scheme Alembic-watchOS -configuration Release -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch - 38mm' | xcpretty -c
  - xcodebuild test -scheme Alembic-tvOS -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty -c

notifications:
 email: false
