language: objective-c
osx_image: xcode7.3

env:
  global:
    - LC_CTYPE=en_US.UTF-8

script:
  - pod lib lint --allow-warnings
  - set -o pipefail
  - xcodebuild test -scheme Alembic-OSX | xcpretty -c
  - xcodebuild test -scheme Alembic-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' | xcpretty - c

notifications:
 email: false
