
language: objective-c
osx_image: xcode7.3

env:
  global:
    - LC_CTYPE=en_US.UTF-8

script:
  - pod lib lint --allow-warnings
  - set -o pipefail
  - xcodebuild test -workspace Alembic.xcworkspace -scheme Alembic -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' | xcpretty -c

before_deploy:
  - carthage build --no-skip-current
  - carthage archive Alembic

deploy:
  provider: releases
  api_key: // TODO:
  file: Alembic.framework.zip
  skip_cleanup: true
  on:
    repo: ra1028/Alembic
    tags: true

notifications:
 email: false
